title = 'reissenzahn.github.io'
baseURL = 'https://reissenzahn.com/'
languageCode = 'en-us'

[markup]
  [markup.highlight]
    style = 'xcode'
    tabWidth = 2

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true
